name: Increase NPM package.json version

on:
  push:
    branches:
      - main

jobs:
  increase-version:
    name: NPM version patch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ secrets.CI3AP_GH_TOKEN }}
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Setup git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
      - name: Version patch
        run: npm version patch
      - name: Push changes to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
