name: NPM version increase

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Increase version in package.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
          token: ${{ secrets.PAT_TOKEN }}
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Setup git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
      - name: NPM version patch
        run: npm version patch -m "Upgrade version to v%s; [skip ci]"
      - name: Push changes to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: 'main'
          force_with_lease: true
