name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ secrets.CI3AP_GH_TOKEN }}
          ref: ${{ github.event.release.tag_name }}
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Publish to NPM
        run: npm publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
